#!/usr/bin/env bash
set -e

function build() {
    if [[ -n "$1" ]]; then
        pushd $1
    fi

    yarn install
    yarn clean
    yarn build
    yarn test
    #yarn test-browser
    yarn docs

    if [[ -n "$1" ]]; then
        popd
    fi

}

function package() {
    pushd $1

    rm -rf dist
    mkdir -p dist

    cp -r src/* dist
    cp ../LICENSE dist

    popd
}

function publish() {
    if [[ ! -n "$1" ]]; then
        echo "ERROR: Specify directory"
        exit 1
    fi
    if [[ ! -n "$NPM_TOKEN" ]]; then
        echo "ERROR: Specify NPM_TOKEN"
        exit 1
    fi

    dist=$1/dist

    mkdir -p ${dist}
    cat >${dist}/.npmrc <<EOL
@http4t:registry=https://registry.npmjs.org
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
EOL
    pushd ${dist}
    yarn run bumpVersion
    npm publish --access public
    popd
}

function publishDocs() {
    TMP=/tmp/http4t.github.io/
    rm -rf ${TMP}
    git clone https://${GH_TOKEN}@github.com/http4t/http4t.github.io.git ${TMP}
    moduleName=${PWD##*/}
    if [[ ${moduleName} == "http4t" ]]; then
        echo "ignored"
    elif [[ ${moduleName} == "site" ]]; then
        cp -R dist/docs/ ${TMP}
    else
        mkdir -p ${TMP}/api
        cp -R dist/docs ${TMP}/api/${moduleName}
    fi
    cd ${TMP}
    sed s/\>\</\>`date '+%Y-%m-%d'`\</g sitemap.xml > new ; mv new sitemap.xml
    git add .
    git commit -m "${moduleName} update"
    git push
    cd -
}


function ci() {
    modules=$(ls | grep "http4t-.*")

    for module in $modules; do
        package $module
        publish $module
    done
}

#
#---------------
# script start

export NVM_DIR=$HOME/.nvm

if [[ ! -d $NVM_DIR ]]; then
  mkdir -p $NVM_DIR
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
fi

if [[ ! $(command -v nvm) ]]; then
  set +e
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  set -e
fi

nvm install

if [[ ! $(command -v yarn) ]]; then
    npm install -g yarn
fi


if [[ -d  ".git" ]]; then
    # Have to build in correct order
    build http4t-core
    build http4t-node
    build http4t-browser
    build site
else
    build
fi

if [[ -n "$1" ]]; then
    "$1"
fi
