version: 2.1

jobs:
  contract:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Build & Deploy
          command: ./run ci
workflows:
  version: 2
  build-deploy:
    jobs:
      - contract:
          filters:
            branches:
              only: master
      - store_artifacts:
          path: /home/circleci/.npm/_logs/