version: 2.1

jobs:
  contract:
    docker:
      - image: circleci/node:10
    working_directory: /tmp
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Build & Deploy
          command: ./run ci
      - store_artifacts:
          path: /tmp/.npm/_logs/workflows
workflows:
  version: 2
  build-deploy:
    jobs:
      - contract:
          filters:
            branches:
              only: master
