version: 2.1

jobs:
  contract:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: bidi-example
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: bidi-example
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Build & Deploy
          command: ./run ci
      - store_artifacts:
          path: /home/circleci/.npm/_logs/workflows
workflows:
  version: 2
  build-deploy:
    jobs:
      - contract:
          filters:
            branches:
              only: master
