name: Build
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    name: Test node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: install
        run: yarn install
      - name: test
        run: yarn run test:packages:node
  test-browser:
    runs-on: ubuntu-latest
    name: Browser test
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/
      - name: install
        run: yarn install
      - name: test
        uses: mujo-code/puppeteer-headful@12.3.1
        env:
          CI: 'true'
        with:
          args: yarn run test:packages:browser
  test-examples:
    runs-on: ubuntu-latest
    name: Test examples
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_DB: bidi-example
          POSTGRES_USER: bidi-example
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org/
      - name: install
        run: yarn install
      - name: test
        run: yarn run test:examples
  publish:
    name: Publish
    needs: [ test, test-browser ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: install
        run: yarn install
      - name: version
        run: yarn run version
      - name: publish
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
